# ── AquaOS PoC ──────────────────────────────────────────────────────────
# AWS Free Tier deployment: EC2 t3.micro + S3 + CloudFront
# Region: eu-west-1 (Ireland) — lowest free-tier risk

terraform {
  required_version = ">= 1.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  backend "s3" {
    bucket         = "aquaos-terraform-state"
    key            = "aws/terraform.tfstate"
    region         = "eu-west-1"
    encrypt        = true
    dynamodb_table = "aquaos-terraform-locks"
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "aquaos"
      Environment = "poc"
      ManagedBy   = "terraform"
    }
  }
}

# ── AWS Account / Region Data ───────────────────────────────────────────

data "aws_caller_identity" "current" {}

data "aws_availability_zones" "available" {
  state = "available"
}

# AMI: Amazon Linux 2023 (free-tier eligible, minimal)
data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# ── SSH Key Pair (generated by Terraform) ───────────────────────────────

resource "random_password" "ssh" {
  length  = 32
  special = false
}

resource "aws_key_pair" "aquaos" {
  key_name   = "aquaos-poc"
  public_key = var.ssh_public_key
}

# ── Backend State Resources (one-time manual creation) ──────────────────
# These are commented out because they can't be in the same apply as the
# backend config that references them. Create manually once:
#
#   aws s3 mb s3://aquaos-terraform-state --region eu-west-1
#   aws dynamodb create-table \
#     --table-name aquaos-terraform-locks \
#     --attribute-definitions AttributeName=LockID,AttributeType=S \
#     --key-schema AttributeName=LockID,KeyType=HASH \
#     --billing-mode PAY_PER_REQUEST \
#     --region eu-west-1
